-- Cria o catalogo unico "Produtos": substitui o casamento por NOME DE TEXTO
-- entre Fichas Tecnicas, Estoque e Compras por uma referencia real por ID.
--
-- Motivo (mapeado no codigo antes desta migration): hoje um insumo de ficha
-- e so uma string digitada; se o nome nao bate com nada em `estoque`, o custo
-- daquele insumo fica $0 em silencio, e a unica pista disso so aparece DEPOIS
-- de uma venda, nunca ao montar a ficha. Compras e Estoque tambem so se
-- encontram por nome (`BalancesAndExpensesModule.tsx`), sem nenhum vinculo
-- de verdade.
--
-- ADITIVA DE PROPOSITO, mesmo padrao das migrations anteriores. A tabela
-- `estoque` continua viva e intocada — sera removida numa migration B
-- separada, so depois do catalogo novo estar validado em uso real. Os
-- insumos ja usados em fichas existentes NAO sao religados por esta
-- migration: esse casamento e feito por script revisavel a parte (por nome
-- normalizado, igual `stockConsumption.ts` ja faz hoje), justamente para
-- poder mostrar os casos ambiguos antes de gravar qualquer vinculo.
--
-- Idempotente: pode rodar mais de uma vez sem erro nem duplicar dado.


-- ============================================================================
-- 1. Tabela produtos
-- ============================================================================
--
-- `GENERATED BY DEFAULT AS IDENTITY`, e nao `ALWAYS`: o backfill da secao 3
-- precisa inserir explicitando o MESMO id que o item ja tinha em `estoque`,
-- para que o rastro entre as duas tabelas continue obvio. `ALWAYS` proibiria
-- essa insercao.

CREATE TABLE IF NOT EXISTS public.produtos (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuaria_id             uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,

  nome                   text NOT NULL,

  -- Texto livre de proposito, sem CHECK: a lista de categorias (Massa,
  -- Recheio, Cobertura, Decoracao, Embalagem) e sugestao editavel na UI, nao
  -- uma enumeracao fixa no banco — mesmo padrao ja usado em
  -- despesas_empresa.nome.
  categoria              text,

  preco_pago             numeric NOT NULL DEFAULT 0 CHECK (preco_pago >= 0),
  quantidade_embalagem   numeric NOT NULL DEFAULT 1 CHECK (quantidade_embalagem > 0),
  unidade_embalagem      text NOT NULL DEFAULT 'un',

  -- Custo por unidade NAO e uma coluna: e sempre preco_pago /
  -- quantidade_embalagem, calculado na hora de exibir (financialEngine ou
  -- equivalente). Guardar isso aqui repetiria o erro da antiga coluna
  -- fantasma `administrative_costs.total`, que nunca era reescrita e ficava
  -- errada a cada edicao de preco.

  controla_estoque       boolean NOT NULL DEFAULT true,

  -- So fazem sentido quando controla_estoque = true; ficam NULL quando o
  -- produto e so referencia de preco/conversao (ex: fruta fresca comprada na
  -- hora, sem estoque controlado).
  quantidade_atual       numeric,
  quantidade_referencia  numeric,
  nivel_minimo           numeric,
  nivel_minimo_unidade   text,

  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS produtos_usuaria_idx
  ON public.produtos (usuaria_id, nome);

ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "produtos proprios" ON public.produtos;
CREATE POLICY "produtos proprios" ON public.produtos
  FOR ALL
  USING (auth.uid() = usuaria_id)
  WITH CHECK (auth.uid() = usuaria_id);

COMMENT ON TABLE  public.produtos                     IS 'Catalogo unico de tudo que a confeitaria usa (ingrediente, embalagem, decoracao). Fonte de verdade referenciada por ID em Fichas, Compras e Estoque — substitui o casamento por nome de texto.';
COMMENT ON COLUMN public.produtos.categoria           IS 'Categoria livre (Massa, Recheio, Cobertura, Decoracao, Embalagem sao sugestoes da UI, nao uma lista fixa no banco).';
COMMENT ON COLUMN public.produtos.preco_pago          IS 'Valor pago pela embalagem/unidade de compra inteira. Custo por unidade = preco_pago / quantidade_embalagem, calculado na leitura.';
COMMENT ON COLUMN public.produtos.controla_estoque    IS 'false = produto existe so como referencia de preco/conversao (ex: item fresco comprado na hora), sem quantidade controlada.';
COMMENT ON COLUMN public.produtos.quantidade_referencia IS 'Baseline usado para o arco de percentual na tela de Estoque (equivalente a estoque.quantidade_referencia).';


-- ============================================================================
-- 2. produto_id em transacoes (liga uma compra a um Produto do catalogo)
-- ============================================================================

ALTER TABLE public.transacoes
  ADD COLUMN IF NOT EXISTS produto_id bigint REFERENCES public.produtos (id) ON DELETE SET NULL;

COMMENT ON COLUMN public.transacoes.produto_id IS 'Produto do catalogo que esta compra (reposicao) abastece. NULL em lancamentos que nao se referem a um produto especifico, ou em transacoes anteriores a esta migration.';


-- ============================================================================
-- 3. Backfill: cada item de estoque vira um Produto, com o MESMO id
-- ============================================================================
--
-- preco_pago = preco_unitario e quantidade_embalagem = 1: preserva
-- exatamente o mesmo custo por unidade que o item ja tinha
-- (preco_pago / 1 = preco_unitario), sem reinterpretar o dado existente.
--
-- ON CONFLICT (id) DO NOTHING: torna a migration segura de rodar mais de uma
-- vez sem duplicar produto nem sobrescrever edicao que ja tenha acontecido
-- direto na tabela produtos.

INSERT INTO public.produtos (
  id, usuaria_id, nome, categoria,
  preco_pago, quantidade_embalagem, unidade_embalagem,
  controla_estoque, quantidade_atual, quantidade_referencia,
  nivel_minimo, nivel_minimo_unidade, created_at
)
SELECT
  id, usuaria_id, item, NULL,
  COALESCE(preco_unitario, 0), 1, COALESCE(unidade_medida, 'un'),
  true, quantidade_atual, quantidade_referencia,
  nivel_minimo, nivel_minimo_unidade, created_at
FROM public.estoque
ON CONFLICT (id) DO NOTHING;

-- A tabela usa GENERATED BY DEFAULT AS IDENTITY: o backfill acima insere IDs
-- explicitos, que nao avancam a sequence automaticamente. Sem este ajuste, o
-- proximo INSERT sem id explicito (um produto novo cadastrado pela usuaria)
-- tentaria reusar um id ja ocupado por um item migrado e falharia.
--
-- O terceiro argumento (is_called) evita um buraco quando `estoque` esta
-- vazio: setval(seq, 1) sozinho marcaria o 1 como "ja usado" e o primeiro
-- produto novo nasceria com id=2. Com is_called=false nesse caso, o proximo
-- nextval() devolve exatamente 1. Quando ha linhas migradas, is_called=true
-- e o proximo id continua normalmente depois do maior id existente.
SELECT setval(
  pg_get_serial_sequence('public.produtos', 'id'),
  COALESCE((SELECT MAX(id) FROM public.produtos), 1),
  (SELECT MAX(id) FROM public.produtos) IS NOT NULL
);
